// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelBrokerImage } from "./ModelBrokerImage";

export type ModelBrokerMessage = { role: string, content: string, images?: Array<ModelBrokerImage>, };
