// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { ResponseInputItem } from "../ResponseInputItem";
import type { ResponseItem } from "../ResponseItem";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ModelBrokerMessage } from "./ModelBrokerMessage";

export type ModelBrokerCall = { id?: string | null, instructions?: string | null, messages: Array<ModelBrokerMessage>, model?: string | null, reasoningEffort?: ReasoningEffort | null, reasoningSummary?: ReasoningSummary | null, serviceTier?: string | null | null, outputSchema?: JsonValue | null, tools?: Array<JsonValue>, toolChoice?: string | null, parallelToolCalls?: boolean | null, previousResponseId?: string | null, replayItems?: Array<ResponseItem>, inputItems?: Array<ResponseInputItem>, };
