// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseItem } from "../ResponseItem";
import type { TokenUsage } from "../TokenUsage";
import type { ModelBrokerFunctionCall } from "./ModelBrokerFunctionCall";

export type ModelBrokerResult = { id?: string | null, text: string, responseId?: string | null, tokenUsage?: TokenUsage | null, model: string, outputItems?: Array<ResponseItem>, functionCalls?: Array<ModelBrokerFunctionCall>, };
