// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelBrokerFunctionCall = { id?: string | null, name: string, namespace?: string | null, arguments: string, callId: string, };
