// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallToolResult } from "./CallToolResult";
import type { ContentItem } from "./ContentItem";
import type { FunctionCallOutputBody } from "./FunctionCallOutputBody";
import type { MessagePhase } from "./MessagePhase";

export type ResponseInputItem = { "type": "message", role: string, content: Array<ContentItem>, phase?: MessagePhase, } | { "type": "function_call_output", call_id: string, output: FunctionCallOutputBody, } | { "type": "mcp_tool_call_output", call_id: string, output: CallToolResult, } | { "type": "custom_tool_call_output", call_id: string, name?: string, output: FunctionCallOutputBody, } | { "type": "tool_search_output", call_id: string, status: string, execution: string, tools: unknown[], };
